# Generated by Django 3.1.2 on 2021-11-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211109_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf'),
        ),
    ]
