# Generated by Django 3.1.2 on 2021-11-09 22:54

import django.core.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
