# Generated by Django 3.1.2 on 2021-11-10 09:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211109_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
