# Generated by Django 3.1.2 on 2021-11-10 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211110_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
