# Generated by Django 3.1.2 on 2021-11-10 12:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211110_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
    ]
