# Generated by Django 3.1.2 on 2021-11-10 12:14

from django.db import migrations
import jsonfield.fields
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20211110_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=jsonfield.fields.JSONField(blank=True, default={'name': store.models.Product}, null=True),
        ),
    ]
