# Generated by Django 3.1.2 on 2021-11-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20211110_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='Geneal', max_length=50),
        ),
    ]
